// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UserToDoItems.Models;

namespace UserToDoItems.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20180705041848_One-One")]
    partial class OneOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserToDoItems.Models.Login", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<int>("UserID");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("UserToDoItems.Models.ToDoItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("UserToDoItems.Models.ToDoUsers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("ToDoUsers");
                });

            modelBuilder.Entity("UserToDoItems.Models.Login", b =>
                {
                    b.HasOne("UserToDoItems.Models.ToDoUsers", "User")
                        .WithOne("Login")
                        .HasForeignKey("UserToDoItems.Models.Login", "UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UserToDoItems.Models.ToDoItem", b =>
                {
                    b.HasOne("UserToDoItems.Models.ToDoUsers", "User")
                        .WithMany("ToDoItems")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
